name: Auto Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 进入项目目录
            cd /www/bruce-nodejs

            # 拉取最新代码
            git fetch origin main

            # 强制让本地当前分支 + 工作区，完全对齐远程 origin/main
            git reset --hard origin/main

            # 安装所有依赖（包含 devDependencies，TS编译需要）
            npm ci

            # 安装依赖（npm ci 锁版本，比 npm install 更适合CI）
            npm ci

            # 优先生成 Prisma 客户端 & 类型（解决TS找不到字段问题）
            npx prisma generate

            # 执行数据库生产迁移
            npx prisma migrate deploy

            # 3. PM2 重启/启动服务
            pm2 restart ecosystem.config.cjs || pm2 start ecosystem.config.cjs

            # 把最新进程状态写入快照(服务器重启的时候 pm2 会读取快照来重启服务)
            pm2 save
